### ISSUE TITLE
Screenshot doesn't show visual styles

### ISSUE THREAD

**Issue by josephcsible** [sjmulder/netwake#1]
The readme says this:

> Theme support ('visual styles') on Windows XP and up.

But this isn't working in your screenshot from Windows XP. It looks like the "Classic Windows" screenshot from https://www.codeproject.com/Articles/5107/Applying-Windows-XP-Visual-Styles-to-Applications, not the "Windows XP Themes" screenshot.

**Comment by sjmulder** [comment]
For the screenshot I had Windows XP set to the classic theme because that’s my own preference. While the XP shots don’t demo the theme support, they do show the font scaling support.

Instead the Windows 8 and 10 screenshots do show the visual styles. Without theming support those would look like the XP screenshot (e.g. not the gradient/flat buttons).

Edit: I’ll close the issue but if I misunderstood your point or if anything is unclear, feel free to comment
